seed: 0
keep_incomplete: False
latent_dim: 64

wandb_project: incomplete_MHD
config_name: incomplete_mhd 
project_path: ./incomplete_mhd_expes_clean/

defaults:
  - datasets: incomplete
  - trainer: base 
  - model: mvtcae
  - encoders: base
  - decoders: base
  - dcca_networks: base
  - joint_encoder: base

