_target_: multivae.models.MMVAE
encoders: ??
decoders: ??
model_config: 
  _target_: multivae.models.MMVAEConfig
  beta: 0.5
  uses_likelihood_rescaling: True
  K: 10
  prior_and_posterior_dist: laplace_with_softmax
  learn_prior: False

  n_modalities: 3
  latent_dim: ${latent_dim}
  input_dims:
    image: [3,28,28]
    audio: [1,32,128]
    trajectory: [200]